export const URL_API = "https://movienew.cybersoft.edu.vn";
export const GPOUP_ID = "GP01";
export const TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5Mb3AiOiJCb290Y2FtcCDEkMOgIE7hurVuZyAwMyIsIkhldEhhblN0cmluZyI6IjI3LzAxLzIwMjMiLCJIZXRIYW5UaW1lIjoiMTY3NDc3NzYwMDAwMCIsIm5iZiI6MTY0NTgwODQwMCwiZXhwIjoxNjc0OTI1MjAwfQ.LrAtwphIhIIrGz5ssg4cQOfyHiF8X8oDbkMMa8YAebQ";
